<a href="https://colab.research.google.com/github/KayalvizhiT513/SVD-Algorithm/blob/main/SVD_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import svd

##Implementation of SVD

In [2]:
def svd_implemented(A):
    # Compute eigenvalues and eigenvectors of A^T * A
    eigenvalues, V = np.linalg.eig(np.dot(A.T, A))

    # Sort eigenvalues in descending order
    descending_order = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[descending_order]
    V = V[:, descending_order]

    # Compute singular values
    singular_values = np.sqrt(eigenvalues)

    # Compute left singular vectors
    U = np.dot(A, V) / singular_values

    return U, singular_values, V.T


In [15]:
A = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])
U, Sigma, V = svd_implemented(A)
U3 = np.real(U[:,:3])
S3 = np.diag(np.real(Sigma[:3]))
VT3 = V[:3]
print("U:\n", U3)
print("Sigma:\n", S3)
print("VT:\n", VT3)

U:
 [[ 0.13759913  0.02361145 -0.01080847]
 [ 0.41279738  0.07083435 -0.03242542]
 [ 0.5503965   0.09444581 -0.04323389]
 [ 0.68799563  0.11805726 -0.05404236]
 [ 0.15277509 -0.59110096  0.65365084]
 [ 0.07221651 -0.73131186 -0.67820922]
 [ 0.07638754 -0.29555048  0.32682542]]
Sigma:
 [[12.48101469  0.          0.        ]
 [ 0.          9.50861406  0.        ]
 [ 0.          0.          1.34555971]]
VT:
 [[ 0.56225841  0.5928599   0.56225841  0.09013354  0.09013354]
 [ 0.12664138 -0.02877058  0.12664138 -0.69537622 -0.69537622]
 [-0.40966748  0.80479152 -0.40966748 -0.0912571  -0.0912571 ]]


<ipython-input-2-df51f6ce4e5c>:11: RuntimeWarning: invalid value encountered in sqrt
  singular_values = np.sqrt(eigenvalues)


###Reverting to Original matrix

In [16]:
(U3 @ S3) @ VT3

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         8.65182035e-18,  8.65182035e-18],
       [ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
         6.59140281e-17,  6.59140281e-17],
       [ 4.00000000e+00,  4.00000000e+00,  4.00000000e+00,
         3.46072814e-17,  3.46072814e-17],
       [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
        -8.51703625e-17, -8.51703625e-17],
       [ 9.60983786e-16,  2.00000000e+00,  3.28945631e-16,
         4.00000000e+00,  4.00000000e+00],
       [-1.10073737e-15, -9.20809971e-16,  1.75126627e-15,
         5.00000000e+00,  5.00000000e+00],
       [ 4.80491893e-16,  1.00000000e+00,  1.64472815e-16,
         2.00000000e+00,  2.00000000e+00]])

##Result of build in function

In [18]:
A = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])
U, Sigma, VT = svd(A)
U3 = np.real(U[:,:3])
S3 = np.diag(np.real(Sigma[:3]))
VT3 = VT[:3]
print("U:\n", U3)
print("Sigma:\n", S3)
print("VT:\n", VT3)

U:
 [[-0.13759913 -0.02361145 -0.01080847]
 [-0.41279738 -0.07083435 -0.03242542]
 [-0.5503965  -0.09444581 -0.04323389]
 [-0.68799563 -0.11805726 -0.05404236]
 [-0.15277509  0.59110096  0.65365084]
 [-0.07221651  0.73131186 -0.67820922]
 [-0.07638754  0.29555048  0.32682542]]
Sigma:
 [[12.48101469  0.          0.        ]
 [ 0.          9.50861406  0.        ]
 [ 0.          0.          1.34555971]]
VT:
 [[-0.56225841 -0.5928599  -0.56225841 -0.09013354 -0.09013354]
 [-0.12664138  0.02877058 -0.12664138  0.69537622  0.69537622]
 [-0.40966748  0.80479152 -0.40966748 -0.0912571  -0.0912571 ]]


##Reverting to Original Matrix


In [19]:
(U3 @ S3) @ VT3

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -8.49349498e-17, -8.65495965e-17],
       [ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
        -4.34636903e-16, -4.39480843e-16],
       [ 4.00000000e+00,  4.00000000e+00,  4.00000000e+00,
        -4.34823981e-16, -4.41282568e-16],
       [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
        -6.46621403e-16, -6.54694636e-16],
       [-2.87685848e-16,  2.00000000e+00, -1.51094123e-15,
         4.00000000e+00,  4.00000000e+00],
       [-6.31227196e-17,  1.16816556e-16, -5.46038205e-16,
         5.00000000e+00,  5.00000000e+00],
       [-1.43842924e-16,  1.00000000e+00, -7.55470615e-16,
         2.00000000e+00,  2.00000000e+00]])